import { PDFDocument,StandardFonts,rgb } from 'pdf-lib';
import type { ReimbursementData,ReceiptItem,SignatureImages } from '../types/reimbursement';
import { fieldCoordinates as c } from './fieldCoordinates';
import { drawCheckbox,drawMultilineText,drawTextField } from './drawHelpers';
import { appendReceipts } from './appendReceipts';
import { formatCurrency,formatDate,normalizeEmail } from '../utils/formatUtils';
export const TEMPLATE_URL=`${import.meta.env.BASE_URL}assets/Remboursement%20Achat.pdf`;
export const generatePdf=async(data:ReimbursementData,receipts:ReceiptItem[]=[],calibration=false,signatures:SignatureImages={})=>{const response=await fetch(TEMPLATE_URL);if(!response.ok)throw new Error('Le PDF modèle est introuvable.');const out=await PDFDocument.load(await response.arrayBuffer());const page=out.getPage(0),font=await out.embedFont(StandardFonts.Helvetica);const text=(key:keyof typeof c,value:string)=>drawTextField(page,value,c[key] as never,font);const check=(key:keyof typeof c,on:boolean)=>on&&drawCheckbox(page,c[key] as never);
 const signature=async(key:'presidentSignature'|'treasurerSignature',file?:File)=>{if(!file)return;const image=await out.embedPng(await file.arrayBuffer());const p=c[key],scale=Math.min(p.width/image.width,(p.height||30)/image.height);const width=image.width*scale,height=image.height*scale;page.drawImage(image,{x:p.x+(p.width-width)/2,y:p.y+((p.height||30)-height)/2,width,height});};
 text('groupName',data.groupName);check(`group${data.groupType==='technical'?'Technical':data.groupType==='ageg'?'Ageg':data.groupType==='promo'?'Promo':'PromoCsg'}` as keyof typeof c,true);text('reimburseTo',data.reimburseTo);check(data.refundMethod==='accesd'?'methodAccesd':'methodCheque',true);text('contact',data.contact);text('phone',data.phone);text('email',normalizeEmail(data.email).replace('@usherbrooke.ca',''));text('amount',formatCurrency(data.amount));
 const pm={fundraising:'purchaseFundraising',revenue:'purchaseRevenue',noRevenue:'purchaseNoRevenue',other:'purchaseOther'} as const;data.purchaseTypes.forEach(v=>check(pm[v],true));if(data.purchaseTypes.includes('other'))text('otherDate',formatDate(data.otherDate));check('equipment',data.equipment);check('computerEquipment',data.computerEquipment);check('itemOver2000',data.itemOver2000);check('itemOver1500',data.itemOver1500);if(data.equipmentLife)check(`equipmentLife${data.equipmentLife}` as keyof typeof c,true);if(data.computerLife)check(`computerLife${data.computerLife}` as keyof typeof c,true);text('project',data.project);drawMultilineText(page,data.description,c.description,font);text('president',data.president);text('treasurer',data.treasurer);await signature('presidentSignature',signatures.president);await signature('treasurerSignature',signatures.treasurer);text('submittedDate',formatDate(data.submittedDate));
 if(calibration){for(const [name,p] of Object.entries(c)){page.drawRectangle({x:p.x,y:p.y,width:'width'in p?p.width:p.size,height:'height'in p?(p.height||12):'size'in p?p.size:12,borderColor:rgb(1,0,0),borderWidth:.6,opacity:.15});page.drawText(name,{x:p.x,y:p.y+('height'in p?(p.height||12):12),size:5,font,color:rgb(1,0,0)});}}
 if(!calibration)await appendReceipts(out,receipts);return out.save();};
