import type { ReimbursementData,ValidationErrors,PurchaseType,SignatureImages } from '../types/reimbursement';
type Props={data:ReimbursementData;errors:ValidationErrors;signatures:SignatureImages;onChange:(patch:Partial<ReimbursementData>)=>void;onSignatureChange:(role:keyof SignatureImages,file?:File)=>void;onClear:()=>void};
const ErrorText=({text}:{text?:string})=>text?<span className="error" role="alert">{text}</span>:null;
export function ReimbursementForm({data,errors,signatures,onChange,onSignatureChange,onClear}:Props){const field=(key:keyof ReimbursementData)=>(e:React.ChangeEvent<HTMLInputElement|HTMLTextAreaElement|HTMLSelectElement>)=>onChange({[key]:e.target.value} as Partial<ReimbursementData>);const togglePurchase=(v:PurchaseType)=>onChange({purchaseTypes:data.purchaseTypes.includes(v)?data.purchaseTypes.filter(x=>x!==v):[...data.purchaseTypes,v]});return <>
 <section><h2>Informations générales</h2><div className="grid two">
  <label>Nom du groupe *<input value={data.groupName} onChange={field('groupName')} aria-invalid={!!errors.groupName}/><ErrorText text={errors.groupName}/></label>
  <fieldset><legend>Type de groupe</legend>{[['technical','Gr. Technique'],['ageg','Gr. AGEG'],['promo','Promo'],['promoCsg','Promo CSG']].map(([v,l])=><label className="choice" key={v}><input type="radio" checked={data.groupType===v} onChange={()=>onChange({groupType:v as ReimbursementData['groupType']})}/>{l}</label>)}</fieldset>
  <label>Rembourser à *<input value={data.reimburseTo} onChange={field('reimburseTo')} aria-invalid={!!errors.reimburseTo}/><ErrorText text={errors.reimburseTo}/></label>
  <fieldset><legend>Méthode</legend><label className="choice"><input type="radio" checked={data.refundMethod==='accesd'} onChange={()=>onChange({refundMethod:'accesd'})}/>Inscrit Accès D</label><label className="choice"><input type="radio" checked={data.refundMethod==='cheque'} onChange={()=>onChange({refundMethod:'cheque'})}/>Chèque</label></fieldset>
  <label>Contact du groupe *<input value={data.contact} onChange={field('contact')} aria-invalid={!!errors.contact}/><ErrorText text={errors.contact}/></label><label>Téléphone<input inputMode="tel" value={data.phone} onChange={field('phone')}/></label>
  <label>Courriel *<span className="email"><input value={data.email} onChange={field('email')} aria-invalid={!!errors.email}/><small>@usherbrooke.ca est ajouté au besoin</small></span><ErrorText text={errors.email}/></label>
 </div></section>
 <section><h2>Achat</h2><div className="grid two"><label>Montant à rembourser *<input inputMode="decimal" value={data.amount} onChange={field('amount')} placeholder="0,00" aria-invalid={!!errors.amount}/><ErrorText text={errors.amount}/></label>
 <fieldset><legend>Type d’achat *</legend>{([['fundraising','Activité de financement'],['revenue','Activité avec revenu relié'],['noRevenue','Activité sans revenu'],['other','Autre / Compétition, conférence, etc.']] as [PurchaseType,string][]).map(([v,l])=><label className="choice" key={v}><input type="checkbox" checked={data.purchaseTypes.includes(v)} onChange={()=>togglePurchase(v)}/>{l}</label>)}<ErrorText text={errors.purchaseTypes}/>{data.purchaseTypes.includes('other')&&<label>Date<input type="date" value={data.otherDate} onChange={field('otherDate')}/></label>}</fieldset>
 <fieldset className="span2"><legend>Équipement</legend><label className="choice"><input type="checkbox" checked={data.equipment} onChange={e=>onChange({equipment:e.target.checked})}/>Équipement</label><label className="choice"><input type="checkbox" checked={data.itemOver2000} onChange={e=>onChange({itemOver2000:e.target.checked})}/>Valeur de 2 000 $ et plus pour un item</label><label>Durée de vie<select value={data.equipmentLife} onChange={field('equipmentLife')}><option value="">—</option><option value="2">2 ans</option><option value="3">3 ans</option><option value="5">5 ans</option></select></label><label className="choice"><input type="checkbox" checked={data.computerEquipment} onChange={e=>onChange({computerEquipment:e.target.checked})}/>Équipement informatique</label><label className="choice"><input type="checkbox" checked={data.itemOver1500} onChange={e=>onChange({itemOver1500:e.target.checked})}/>Valeur de 1 500 $ et plus pour un item</label><label>Durée de vie informatique<select value={data.computerLife} onChange={field('computerLife')}><option value="">—</option><option value="2">2 ans</option><option value="3">3 ans</option><option value="5">5 ans</option></select></label></fieldset></div></section>
 <section><h2>Projet et description</h2><label>Projet / Activité *<input value={data.project} onChange={field('project')} aria-invalid={!!errors.project}/><ErrorText text={errors.project}/></label><label>Description de l’achat *<textarea rows={4} value={data.description} onChange={field('description')} aria-invalid={!!errors.description}/><ErrorText text={errors.description}/><ErrorText text={errors.descriptionOverflow}/></label></section>
 <section><h2>Autorisations</h2><p className="muted">Noms en lettres moulées. Les signatures PNG sont facultatives et ne sont jamais mémorisées. Les champs de l’administration demeurent vides.</p><div className="grid three"><label>Président du groupe *<input value={data.president} onChange={field('president')} aria-invalid={!!errors.president}/><ErrorText text={errors.president}/></label><label>Trésorier du groupe *<input value={data.treasurer} onChange={field('treasurer')} aria-invalid={!!errors.treasurer}/><ErrorText text={errors.treasurer}/></label><label>Date de remise<input type="date" value={data.submittedDate} onChange={field('submittedDate')}/></label><label>Signature du président — facultative<input type="file" accept="image/png,.png" onChange={e=>onSignatureChange('president',e.target.files?.[0])}/>{signatures.president&&<small>{signatures.president.name} <button type="button" className="link-button" onClick={()=>onSignatureChange('president')}>Retirer</button></small>}</label><label>Signature du trésorier — facultative<input type="file" accept="image/png,.png" onChange={e=>onSignatureChange('treasurer',e.target.files?.[0])}/>{signatures.treasurer&&<small>{signatures.treasurer.name} <button type="button" className="link-button" onClick={()=>onSignatureChange('treasurer')}>Retirer</button></small>}</label></div></section>
 <section><h2>Mémorisation</h2><label className="choice"><input type="checkbox" checked={data.remember} onChange={e=>onChange({remember:e.target.checked})}/>Mémoriser mes informations pour la prochaine demande</label><button type="button" className="secondary" onClick={onClear}>Effacer les informations mémorisées</button></section>
 </>}
