import { useEffect,useMemo,useState } from 'react';
import { PDFDocument,StandardFonts } from 'pdf-lib';
import { ReimbursementForm } from './components/ReimbursementForm';
import { ReceiptUploader } from './components/ReceiptUploader';
import { ReceiptList } from './components/ReceiptList';
import { TemplateUploader } from './components/TemplateUploader';
import { PdfPreview } from './components/PdfPreview';
import { ValidationSummary } from './components/ValidationSummary';
import type { ReceiptItem,ReimbursementData,SignatureImages,TemplatePdf,ValidationErrors } from './types/reimbursement';
import { clearSavedFields,loadFields,saveFields } from './storage/savedFields';
import { todayIso,parseAmount,sanitizeFilename } from './utils/formatUtils';
import { generatePdf } from './pdf/generateReimbursementPdf';
import { multilineLayout } from './pdf/drawHelpers';
import { fieldCoordinates } from './pdf/fieldCoordinates';

const initial:ReimbursementData={groupName:'',groupType:'technical',reimburseTo:'',refundMethod:'accesd',contact:'',phone:'',email:'',amount:'',purchaseTypes:[],otherDate:'',equipment:false,computerEquipment:false,itemOver2000:false,itemOver1500:false,equipmentLife:'',computerLife:'',project:'',description:'',president:'',treasurer:'',submittedDate:todayIso(),remember:true,...loadFields()};
const validate=async(d:ReimbursementData,receipts:ReceiptItem[])=>{const e:ValidationErrors={};const req:[keyof ReimbursementData,string][]=[['groupName','Le nom du groupe est vide.'],['reimburseTo','La personne ou compagnie à rembourser est vide.'],['contact','Le contact du groupe est vide.'],['email','Le courriel est vide.'],['amount','Le montant est vide.'],['project','Le projet ou l’activité est vide.'],['description','La description est vide.'],['president','Le président est vide.'],['treasurer','Le trésorier est vide.']];req.forEach(([k,m])=>{if(!String(d[k]).trim())e[k]=m});if(d.amount&&!Number.isFinite(parseAmount(d.amount)))e.amount='Le montant ne semble pas valide.';if(!d.purchaseTypes.length)e.purchaseTypes='Aucun type d’achat n’est sélectionné.';if(!receipts.length)e.receipts='Aucune facture n’est ajoutée.';if(d.description){const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica);if(multilineLayout(d.description,font,fieldCoordinates.description).overflow)e.descriptionOverflow='La description dépasse les trois lignes disponibles et sera tronquée.'}return e};

export default function App(){
 const[data,setData]=useState(initial),[receipts,setReceipts]=useState<ReceiptItem[]>([]),[template,setTemplate]=useState<TemplatePdf>(),[signatures,setSignatures]=useState<SignatureImages>({}),[errors,setErrors]=useState<ValidationErrors>({}),[preview,setPreview]=useState<Uint8Array>(),[previewBusy,setPreviewBusy]=useState(false),[busy,setBusy]=useState(false),[warningsPending,setWarningsPending]=useState(false),[message,setMessage]=useState('');
 const debug=useMemo(()=>new URLSearchParams(location.search).get('debugPdf')==='1',[]);
 useEffect(()=>{let cancelled=false;const timer=setTimeout(()=>{setPreviewBusy(true);saveFields(data);generatePdf(data,receipts,false,signatures,template?.file).then(bytes=>{if(!cancelled)setPreview(bytes)}).catch(e=>{if(!cancelled)setMessage(e.message)}).finally(()=>{if(!cancelled)setPreviewBusy(false)})},700);return()=>{cancelled=true;clearTimeout(timer)}},[data,receipts,signatures,template]);
 const patch=(p:Partial<ReimbursementData>)=>{setData(d=>({...d,...p}));setWarningsPending(false);setErrors(e=>{const n={...e};Object.keys(p).forEach(k=>delete n[k as keyof ValidationErrors]);return n})};
 const updateSignature=(role:keyof SignatureImages,file?:File)=>{if(file&&!((file.type==='image/png')||file.name.toLowerCase().endsWith('.png'))){setMessage('La signature doit être une image PNG.');return}setSignatures(s=>({...s,[role]:file}));setMessage(file?'Signature PNG ajoutée.':'Signature retirée.')};
 const generate=async(calibration=false,ignoreWarnings=false)=>{setBusy(true);setMessage('');try{if(!calibration&&!ignoreWarnings){const found=await validate(data,receipts);setErrors(found);if(Object.keys(found).length){setWarningsPending(true);setTimeout(()=>document.getElementById('warning-confirm')?.scrollIntoView({behavior:'smooth',block:'center'}));return}}setWarningsPending(false);const bytes=await generatePdf(data,calibration?[]:receipts,calibration,calibration?{}:signatures,template?.file);setPreview(bytes);if(!calibration){const blob=new Blob([new Uint8Array(bytes).buffer],{type:'application/pdf'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`Remboursement_${sanitizeFilename(data.groupName)}_${todayIso()}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('Le PDF a été généré et téléchargé.')}}catch(e){setMessage(e instanceof Error?e.message:'Une erreur est survenue.')}finally{setBusy(false)}};
 return <>
  <header className="site-header"><div className="header-inner"><img className="emus-logo" src={`${import.meta.env.BASE_URL}assets/logo-emus.png`} alt="EMUS"/><div className="header-copy"><p className="eyebrow">Outil local et confidentiel</p><h1>Demande de remboursement - AGEG</h1><p className="credit">Gracieuseté de l’équipe EMUS <span>(le meilleur groupe technique)</span></p><p className="author">Par Renaud Gagnon</p></div><span className="privacy">Aucun envoi sur Internet</span></div></header>
  <main><div className="content"><div className="notice"><strong>Vos documents restent ici.</strong> Les informations, le modèle et les factures sont traités localement dans votre navigateur.</div><TemplateUploader template={template} onChange={setTemplate} onMessage={setMessage}/><ReimbursementForm data={data} errors={errors} signatures={signatures} onChange={patch} onSignatureChange={updateSignature} onClear={()=>{clearSavedFields();setMessage('Les informations mémorisées ont été effacées.')}}/><section><h2>Factures</h2><p className="muted">Elles apparaissent dans l’aperçu à droite après leur traitement. Les gros fichiers peuvent demander davantage de mémoire.</p><ReceiptUploader items={receipts} onChange={v=>{setReceipts(v);setWarningsPending(false)}} onMessage={setMessage}/><span className="field-warning">{errors.receipts&&`⚠ ${errors.receipts}`}</span><ReceiptList items={receipts} onChange={v=>{setReceipts(v);setWarningsPending(false)}}/></section><ValidationSummary errors={errors}/>{warningsPending&&<div id="warning-confirm" className="warning-confirm"><strong>Le formulaire contient des éléments à vérifier.</strong><p>Vous pouvez les corriger ou générer le document tel quel.</p><div className="confirm-actions"><button type="button" onClick={()=>setWarningsPending(false)}>Retour au formulaire</button><button type="button" className="primary" disabled={busy} onClick={()=>generate(false,true)}>Ignorer et générer</button></div></div>}<div className="generate"><button className="primary" disabled={busy} onClick={()=>generate(false,false)}>{busy?'Génération en cours…':'Générer et télécharger le PDF'}</button>{message&&<p role="status">{message}</p>}</div></div>
   <aside className="preview-column"><section className="preview-panel"><div className="preview-heading"><div><p className="eyebrow">Document complet</p><h2>{debug?'Calibration PDF':'Aperçu'}</h2></div>{previewBusy&&<span className="preview-status">Mise à jour…</span>}</div><p className="preview-instruction">Le modèle rempli, ses pages supplémentaires et toutes les factures sont affichés ici. Cliquez sur une page pour l’agrandir.</p><PdfPreview bytes={preview} debug={debug}/>{debug&&<button disabled={busy} onClick={()=>generate(true)}>Générer le PDF de calibration</button>}</section></aside>
  </main><footer>EMUS · Moto électrique de l’Université de Sherbrooke</footer>
 </>
}
